// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SearchSubdirectory(arg1) {
  return window['go']['main']['App']['SearchSubdirectory'](arg1);
}
