// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHomeDirectory():Promise<string>;

export function OpenFile(arg1:string):Promise<void>;

export function Search(arg1:main.SearchOptions):Promise<Array<main.FileResult>>;

export function SearchSubdirectory(arg1:string):Promise<Array<main.FileResult>>;
